import streamlit as st
from csv_loader import CSVLoader
from eda import EDA

class StreamlitApp:
    def __init__(self, file_path):
        self.file_path = file_path
        self.loader = CSVLoader(self.file_path)
        self.loader.load_csv()
        self.loader.validate_csv()
        self.eda = EDA(self.loader.data)

    def display_statistics(self):
        st.write(self.eda.statistics)

    def display_visualizations(self):
        # Display the visualizations generated by the EDA
        pass

    def run(self):
        self.eda.calculate_statistics()
        self.display_statistics()
        self.eda.generate_visualizations()
        self.display_visualizations()
